-- ------------------------- info -------------------------
-- @@ver: 1_000_000
-- @@info: 初始化fa-app模块
-- ------------------------- info -------------------------

-- ----------------------------
-- Table structure for app_apk
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_apk" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "application_id" varchar(255) NOT NULL,
  "version_code" integer NOT NULL,
  "version_name" varchar(255) NOT NULL,
  "icon_id" varchar(32) NOT NULL,
  "file_id" varchar(32) NOT NULL,
  "size" bigint DEFAULT NULL,
  "short_code" varchar(4) NOT NULL,
  "remark" text,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "app_apk" IS 'APP-APK表';
COMMENT ON COLUMN "app_apk"."id" IS 'ID';
COMMENT ON COLUMN "app_apk"."name" IS '应用名称';
COMMENT ON COLUMN "app_apk"."application_id" IS '应用包名';
COMMENT ON COLUMN "app_apk"."version_code" IS '当前版本号';
COMMENT ON COLUMN "app_apk"."version_name" IS '当前版本名称';
COMMENT ON COLUMN "app_apk"."icon_id" IS '图标文件ID';
COMMENT ON COLUMN "app_apk"."file_id" IS 'APK文件ID';
COMMENT ON COLUMN "app_apk"."size" IS '文件大小';
COMMENT ON COLUMN "app_apk"."short_code" IS '短链';
COMMENT ON COLUMN "app_apk"."remark" IS '最近版本信息';
COMMENT ON COLUMN "app_apk"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_apk"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_apk"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_apk"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_apk"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_apk"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_apk"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_apk"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_apk"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "app_apk__upd_time" ON "app_apk";
CREATE TRIGGER "app_apk__upd_time" BEFORE UPDATE ON "app_apk" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for app_apk_crash
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_apk_crash" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "application_id" varchar(255) NOT NULL,
  "version_code" integer NOT NULL,
  "version_name" varchar(255) NOT NULL,
  "message" text,
  "detail" text,
  "crash_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "rom_info" varchar(255) DEFAULT NULL,
  "device_manufacturer" varchar(255) DEFAULT NULL,
  "device_model" varchar(255) DEFAULT NULL,
  "android_version" varchar(32) DEFAULT NULL,
  "android_sdk" integer DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "app_apk_crash" IS 'APP-APK崩溃日志表';
COMMENT ON COLUMN "app_apk_crash"."id" IS 'ID';
COMMENT ON COLUMN "app_apk_crash"."app_id" IS '应用ID';
COMMENT ON COLUMN "app_apk_crash"."name" IS '名称';
COMMENT ON COLUMN "app_apk_crash"."application_id" IS '应用包名';
COMMENT ON COLUMN "app_apk_crash"."version_code" IS '版本号';
COMMENT ON COLUMN "app_apk_crash"."version_name" IS '版本名称';
COMMENT ON COLUMN "app_apk_crash"."message" IS '错误日志';
COMMENT ON COLUMN "app_apk_crash"."detail" IS '崩溃日志详情';
COMMENT ON COLUMN "app_apk_crash"."crash_time" IS '崩溃时间';
COMMENT ON COLUMN "app_apk_crash"."rom_info" IS 'rom信息';
COMMENT ON COLUMN "app_apk_crash"."device_manufacturer" IS '设备厂商';
COMMENT ON COLUMN "app_apk_crash"."device_model" IS '设备型号';
COMMENT ON COLUMN "app_apk_crash"."android_version" IS 'android版本';
COMMENT ON COLUMN "app_apk_crash"."android_sdk" IS 'sdk版本';
COMMENT ON COLUMN "app_apk_crash"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_apk_crash"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_apk_crash"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_apk_crash"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_apk_crash"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_apk_crash"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_apk_crash"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_apk_crash"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_apk_crash"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "app_apk_crash__upd_time" ON "app_apk_crash";
CREATE TRIGGER "app_apk_crash__upd_time" BEFORE UPDATE ON "app_apk_crash" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for app_apk_version
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_apk_version" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "application_id" varchar(255) NOT NULL,
  "version_code" integer NOT NULL,
  "version_name" varchar(255) NOT NULL,
  "icon_id" varchar(32) NOT NULL,
  "file_id" varchar(32) NOT NULL,
  "size" bigint DEFAULT NULL,
  "remark" text,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
COMMENT ON TABLE "app_apk_version" IS 'APP-APK版本表';
COMMENT ON COLUMN "app_apk_version"."id" IS 'ID';
COMMENT ON COLUMN "app_apk_version"."app_id" IS '应用ID';
COMMENT ON COLUMN "app_apk_version"."name" IS '应用名称';
COMMENT ON COLUMN "app_apk_version"."application_id" IS '应用包名';
COMMENT ON COLUMN "app_apk_version"."version_code" IS '版本号';
COMMENT ON COLUMN "app_apk_version"."version_name" IS '版本名称';
COMMENT ON COLUMN "app_apk_version"."icon_id" IS '图标文件ID';
COMMENT ON COLUMN "app_apk_version"."file_id" IS 'APK文件ID';
COMMENT ON COLUMN "app_apk_version"."size" IS '文件大小';
COMMENT ON COLUMN "app_apk_version"."remark" IS '版本信息';
COMMENT ON COLUMN "app_apk_version"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_apk_version"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_apk_version"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_apk_version"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_apk_version"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_apk_version"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_apk_version"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_apk_version"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_apk_version"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "app_apk_version__upd_time" ON "app_apk_version";
CREATE TRIGGER "app_apk_version__upd_time" BEFORE UPDATE ON "app_apk_version" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Records of base_rbac_menu
-- ----------------------------
BEGIN;
INSERT INTO "base_rbac_menu" ("id", "parent_id", "name", "sort", "level", "icon", "status", "link_type", "link_url", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (21000000, 0, 'APP管理', 3, 0, 'mobile-retro', TRUE, 1, '/admin/app', '2023-01-20 14:22:45', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE);

INSERT INTO "base_rbac_menu" ("id", "parent_id", "name", "sort", "level", "icon", "status", "link_type", "link_url", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (21010000, 21000000, 'APP版本管理', 0, 1, 'store', TRUE, 1, '/admin/app/app/apk', '2023-01-20 14:23:14', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE);
INSERT INTO "base_rbac_menu" ("id", "parent_id", "name", "sort", "level", "icon", "status", "link_type", "link_url", "crt_time", "crt_user", "crt_name", "crt_host", "upd_time", "upd_user", "upd_name", "upd_host", "deleted") VALUES (21020000, 21000000, 'APP崩溃日志', 1, 1, 'burst', TRUE, 1, '/admin/app/crash/apkCrash', '2023-01-20 14:23:29', '1', '超级管理员', '127.0.0.1', NULL, NULL, NULL, NULL, FALSE);
COMMIT;

SELECT setval(
    pg_get_serial_sequence('base_rbac_menu', 'id'),
    COALESCE((SELECT MAX("id") FROM "base_rbac_menu"), 1),
    TRUE
);

