-- ------------------------- info -------------------------
-- @@ver: 1_000_006
-- @@info: 增加通用应用版本发布模型
-- ------------------------- info -------------------------

-- ----------------------------
-- Table structure for app_release
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_release" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_id" integer NOT NULL,
  "version_name" varchar(64) NOT NULL,
  "version_code" bigint NOT NULL,
  "channel" varchar(32) NOT NULL DEFAULT 'stable',
  "status" varchar(16) NOT NULL DEFAULT 'DRAFT',
  "force_update" boolean NOT NULL DEFAULT FALSE,
  "min_supported_version_code" bigint,
  "release_note" text,
  "publish_time" timestamp DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32),
  "upd_name" varchar(255),
  "upd_host" varchar(255),
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_app_release_version" UNIQUE ("app_id", "version_code", "channel")
);
CREATE INDEX "idx_app_release_query" ON "app_release" ("app_id", "channel", "status", "version_code");
COMMENT ON TABLE "app_release" IS '应用版本发布记录';
COMMENT ON COLUMN "app_release"."id" IS 'ID';
COMMENT ON COLUMN "app_release"."app_id" IS '应用ID，关联app_apk.id';
COMMENT ON COLUMN "app_release"."version_name" IS '版本名称';
COMMENT ON COLUMN "app_release"."version_code" IS '版本编码';
COMMENT ON COLUMN "app_release"."channel" IS '发布渠道';
COMMENT ON COLUMN "app_release"."status" IS '发布状态：DRAFT/PUBLISHED/REVOKED';
COMMENT ON COLUMN "app_release"."force_update" IS '是否强制更新';
COMMENT ON COLUMN "app_release"."min_supported_version_code" IS '最低支持版本编码';
COMMENT ON COLUMN "app_release"."release_note" IS '更新说明';
COMMENT ON COLUMN "app_release"."publish_time" IS '发布时间';
COMMENT ON COLUMN "app_release"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_release"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_release"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_release"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_release"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_release"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_release"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_release"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_release"."deleted" IS '是否删除';
CREATE TRIGGER "app_release__upd_time" BEFORE UPDATE ON "app_release" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for app_release_package
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_release_package" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "release_id" bigint NOT NULL,
  "platform" varchar(32) NOT NULL,
  "package_type" varchar(16) NOT NULL,
  "base_version_code" bigint,
  "file_id" varchar(64) NOT NULL,
  "size" bigint,
  "sha256" varchar(64) NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32),
  "upd_name" varchar(255),
  "upd_host" varchar(255),
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_app_release_package" UNIQUE ("release_id", "platform", "package_type")
);
CREATE INDEX "idx_app_release_package_query" ON "app_release_package" ("release_id", "platform", "package_type", "base_version_code");
COMMENT ON TABLE "app_release_package" IS '应用版本发布包';
COMMENT ON COLUMN "app_release_package"."id" IS 'ID';
COMMENT ON COLUMN "app_release_package"."release_id" IS '版本发布ID';
COMMENT ON COLUMN "app_release_package"."platform" IS '发布平台：ANDROID/IOS/APP_PLUS/MP_WEIXIN/H5';
COMMENT ON COLUMN "app_release_package"."package_type" IS '包类型：APK/IPA/WGT/FULL';
COMMENT ON COLUMN "app_release_package"."base_version_code" IS '增量包基础版本编码';
COMMENT ON COLUMN "app_release_package"."file_id" IS '文件ID';
COMMENT ON COLUMN "app_release_package"."size" IS '文件大小，单位字节';
COMMENT ON COLUMN "app_release_package"."sha256" IS '文件SHA-256摘要';
COMMENT ON COLUMN "app_release_package"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_release_package"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_release_package"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_release_package"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_release_package"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_release_package"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_release_package"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_release_package"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_release_package"."deleted" IS '是否删除';
CREATE TRIGGER "app_release_package__upd_time" BEFORE UPDATE ON "app_release_package" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
