-- ------------------------- info -------------------------
-- @@ver: 1_000_005
-- @@info: 增加Desktop客户端版本发布模型
-- ------------------------- info -------------------------

-- ----------------------------
-- Table structure for app_client
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_client" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_code" varchar(64) NOT NULL,
  "name" varchar(255) NOT NULL,
  "identifier" varchar(255) NOT NULL,
  "enabled" boolean NOT NULL DEFAULT TRUE,
  "remark" text,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_app_client_code" UNIQUE ("client_code")
);
COMMENT ON TABLE "app_client" IS 'Desktop客户端';
COMMENT ON COLUMN "app_client"."id" IS 'ID';
COMMENT ON COLUMN "app_client"."client_code" IS '客户端标识';
COMMENT ON COLUMN "app_client"."name" IS '客户端名称';
COMMENT ON COLUMN "app_client"."identifier" IS '客户端应用标识';
COMMENT ON COLUMN "app_client"."enabled" IS '是否启用';
COMMENT ON COLUMN "app_client"."remark" IS '备注';
COMMENT ON COLUMN "app_client"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_client"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_client"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_client"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_client"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_client"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_client"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_client"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_client"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "app_client__upd_time" ON "app_client";
CREATE TRIGGER "app_client__upd_time" BEFORE UPDATE ON "app_client" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for app_client_release
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_client_release" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_id" bigint NOT NULL,
  "version_name" varchar(64) NOT NULL,
  "version_code" bigint NOT NULL,
  "channel" varchar(32) NOT NULL DEFAULT 'stable',
  "status" varchar(16) NOT NULL DEFAULT 'DRAFT',
  "release_notes" text,
  "publish_time" timestamp DEFAULT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_app_client_release_version" UNIQUE ("client_id", "version_code", "channel")
);
CREATE INDEX "idx_app_client_release_query" ON "app_client_release" ("client_id", "channel", "status", "version_code");
COMMENT ON TABLE "app_client_release" IS 'Desktop客户端版本';
COMMENT ON COLUMN "app_client_release"."id" IS 'ID';
COMMENT ON COLUMN "app_client_release"."client_id" IS '客户端ID';
COMMENT ON COLUMN "app_client_release"."version_name" IS '版本名称';
COMMENT ON COLUMN "app_client_release"."version_code" IS '版本编码';
COMMENT ON COLUMN "app_client_release"."channel" IS '发布渠道';
COMMENT ON COLUMN "app_client_release"."status" IS '发布状态';
COMMENT ON COLUMN "app_client_release"."release_notes" IS '发布说明';
COMMENT ON COLUMN "app_client_release"."publish_time" IS '发布时间';
COMMENT ON COLUMN "app_client_release"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_client_release"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_client_release"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_client_release"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_client_release"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_client_release"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_client_release"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_client_release"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_client_release"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "app_client_release__upd_time" ON "app_client_release";
CREATE TRIGGER "app_client_release__upd_time" BEFORE UPDATE ON "app_client_release" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();

-- ----------------------------
-- Table structure for app_client_release_artifact
-- ----------------------------

CREATE TABLE IF NOT EXISTS "app_client_release_artifact" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "release_id" bigint NOT NULL,
  "platform" varchar(32) NOT NULL,
  "arch" varchar(32) NOT NULL,
  "file_id" varchar(64) NOT NULL,
  "file_name" varchar(255) DEFAULT NULL,
  "size" bigint DEFAULT NULL,
  "sha256" varchar(64) NOT NULL,
  "signature" text NOT NULL,
  "crt_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "crt_user" varchar(32) NOT NULL,
  "crt_name" varchar(255) NOT NULL,
  "crt_host" varchar(255) DEFAULT NULL,
  "upd_time" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "upd_user" varchar(32) DEFAULT NULL,
  "upd_name" varchar(255) DEFAULT NULL,
  "upd_host" varchar(255) DEFAULT NULL,
  "deleted" boolean NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_app_client_release_artifact" UNIQUE ("release_id", "platform", "arch")
);
CREATE INDEX "idx_app_client_release_artifact_release" ON "app_client_release_artifact" ("release_id");
COMMENT ON TABLE "app_client_release_artifact" IS 'Desktop客户端版本安装包';
COMMENT ON COLUMN "app_client_release_artifact"."id" IS 'ID';
COMMENT ON COLUMN "app_client_release_artifact"."release_id" IS '版本发布ID';
COMMENT ON COLUMN "app_client_release_artifact"."platform" IS '操作系统平台';
COMMENT ON COLUMN "app_client_release_artifact"."arch" IS 'CPU架构';
COMMENT ON COLUMN "app_client_release_artifact"."file_id" IS '安装包文件ID';
COMMENT ON COLUMN "app_client_release_artifact"."file_name" IS '安装包文件名';
COMMENT ON COLUMN "app_client_release_artifact"."size" IS '文件大小，单位字节';
COMMENT ON COLUMN "app_client_release_artifact"."sha256" IS '文件SHA-256';
COMMENT ON COLUMN "app_client_release_artifact"."signature" IS 'Tauri更新签名';
COMMENT ON COLUMN "app_client_release_artifact"."crt_time" IS '创建时间';
COMMENT ON COLUMN "app_client_release_artifact"."crt_user" IS '创建用户ID';
COMMENT ON COLUMN "app_client_release_artifact"."crt_name" IS '创建用户';
COMMENT ON COLUMN "app_client_release_artifact"."crt_host" IS '创建IP';
COMMENT ON COLUMN "app_client_release_artifact"."upd_time" IS '更新时间';
COMMENT ON COLUMN "app_client_release_artifact"."upd_user" IS '更新用户ID';
COMMENT ON COLUMN "app_client_release_artifact"."upd_name" IS '更新用户';
COMMENT ON COLUMN "app_client_release_artifact"."upd_host" IS '更新IP';
COMMENT ON COLUMN "app_client_release_artifact"."deleted" IS '是否删除';
DROP TRIGGER IF EXISTS "app_client_release_artifact__upd_time" ON "app_client_release_artifact";
CREATE TRIGGER "app_client_release_artifact__upd_time" BEFORE UPDATE ON "app_client_release_artifact" FOR EACH ROW EXECUTE FUNCTION fa_base_set_upd_time();
